const MAX_HEADER_LENGTH = 100

const TYPES = [
  { value: 'feat', name: 'feat:     ✨ 新增功能', emoji: '✨' },
  { value: 'fix', name: 'fix:      🐛 修复缺陷', emoji: '🐛' },
  { value: 'docs', name: 'docs:     📝 文档变更', emoji: '📝' },
  { value: 'style', name: 'style:    💄 代码格式调整', emoji: '💄' },
  { value: 'refactor', name: 'refactor: ♻️ 代码重构', emoji: '♻️' },
  { value: 'perf', name: 'perf:     ⚡ 性能或体验优化', emoji: '⚡' },
  { value: 'test', name: 'test:     ✅ 测试相关变更', emoji: '✅' },
  { value: 'build', name: 'build:    📦 构建或依赖变更', emoji: '📦' },
  { value: 'ci', name: 'ci:       🤖 CI/CD 配置变更', emoji: '🤖' },
  { value: 'chore', name: 'chore:    🔧 工程维护或杂项', emoji: '🔧' },
  { value: 'revert', name: 'revert:   ⏪ 回滚提交', emoji: '⏪' },
  { value: 'release', name: 'release:  🚀 版本发布', emoji: '🚀' },
]

const SCOPES = [
  { value: 'app', name: 'app: 应用初始化、布局和全局运行时' },
  { value: 'dashboard', name: 'dashboard: 仪表盘' },
  { value: 'device', name: 'device: 设备中心通用能力' },
  { value: 'device-list', name: 'device-list: 设备管理' },
  { value: 'device-status', name: 'device-status: 设备状态和拓扑' },
  { value: 'device-types', name: 'device-types: 设备类型配置' },
  { value: 'device-log', name: 'device-log: 告警日志' },
  { value: 'device-daily', name: 'device-daily: 数据备份和日报' },
  { value: 'libiio', name: 'libiio: Libiio 设备列表' },
  { value: 'libiio-board', name: 'libiio-board: 频点数据看板' },
  { value: 'libiio-config', name: 'libiio-config: 频点配置' },
  { value: 'admin', name: 'admin: 用户管理' },
  { value: 'setting', name: 'setting: 系统设置' },
  { value: 'user', name: 'user: 登录、回调和用户信息' },
  { value: 'components', name: 'components: 公共组件' },
  { value: 'services', name: 'services: API 请求和接口封装' },
  { value: 'api', name: 'api: 接口定义、请求参数和响应处理' },
  { value: 'typing', name: 'typing: TypeScript 类型定义' },
  { value: 'utils', name: 'utils: 工具函数' },
  { value: 'i18n', name: 'i18n: 国际化和语言包' },
  { value: 'models', name: 'models: 状态模型' },
  { value: 'constants', name: 'constants: 常量配置' },
  { value: 'access', name: 'access: 权限控制' },
  { value: 'styles', name: 'styles: 样式和主题' },
  { value: 'assets', name: 'assets: 静态资源、图片和图标' },
  { value: 'routes', name: 'routes: 路由和菜单' },
  { value: 'config', name: 'config: 项目、代理和环境配置' },
  { value: 'mock', name: 'mock: Mock 数据' },
  { value: 'deps', name: 'deps: 依赖管理' },
  { value: 'build', name: 'build: 构建脚本和产物配置' },
  { value: 'lint', name: 'lint: ESLint、Stylelint 和 Prettier' },
  { value: 'husky', name: 'husky: Git Hooks' },
  { value: 'release', name: 'release: 版本文件和发布产物' },
]

const ISSUE_PREFIXES = [
  { value: 'closed', name: 'closed: 关闭 Issue' },
  { value: 'refs', name: 'refs: 关联 Issue' },
]

const TYPE_VALUES = TYPES.map((item) => item.value)
const SCOPE_VALUES = SCOPES.map((item) => item.value)

module.exports = {
  parserPreset: {
    parserOpts: {
      headerPattern: /^(?:[\p{Extended_Pictographic}\uFE0F\u200D]+\s+)?(\w+)(?:\(([^)]+)\))?!?:\s+(.*)$/u,
      headerCorrespondence: ['type', 'scope', 'subject'],
    },
  },
  rules: {
    'type-enum': [2, 'always', TYPE_VALUES],
    'type-empty': [2, 'never'],
    'scope-enum': [1, 'always', SCOPE_VALUES],
    'scope-case': [2, 'always', ['lower-case', 'kebab-case']],
    'scope-empty': [0],
    'subject-empty': [2, 'never'],
    'subject-case': [0],
    'subject-full-stop': [2, 'never', ['.', '。']],
    'header-max-length': [2, 'always', MAX_HEADER_LENGTH],
    'body-leading-blank': [1, 'always'],
    'footer-leading-blank': [1, 'always'],
  },
  prompt: {
    useEmoji: true,
    emojiAlign: 'left',
    themeColorCode: '',
    messages: {
      type: '选择提交类型:',
      scope: '选择影响范围（可多选，可跳过）:',
      customScope: '填写自定义影响范围:',
      subject: '填写简短说明:',
      body: '填写详细说明，按回车跳过:',
      breaking: '列出破坏性变更，按回车跳过:',
      footerPrefixesSelect: '选择关联 Issue 类型，按回车跳过:',
      customFooterPrefix: '输入自定义 Issue 前缀:',
      footer: '填写关联 Issue，例如 #123，按回车跳过:',
      confirmCommit: '确认生成以上提交信息?',
    },
    types: TYPES,
    scopes: SCOPES,
    enableMultipleScopes: true,
    scopeEnumSeparator: ',',
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    emptyScopesAlias: 'none: 不填写范围',
    customScopesAlias: 'custom: 自定义影响范围',
    allowBreakingChanges: ['feat', 'fix', 'refactor'],
    issuePrefixes: ISSUE_PREFIXES,
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    emptyIssuePrefixAlias: 'skip: 跳过',
    customIssuePrefixAlias: 'custom: 自定义',
    maxHeaderLength: MAX_HEADER_LENGTH,
    breaklineNumber: 100,
    confirmColorize: true,
    subjectLimit: MAX_HEADER_LENGTH,
  },
}
