// @ts-ignore
/* eslint-disable */
/* eslint-disable prettier/prettier */
declare namespace API_USER {
  // Generated by https://quicktype.io

  export interface Result {
    err: number
    msg: string
    res: Res
  }
  export interface Res {
    id: number
    name: string
    account: string
    password: string
    user_id: number
    is_disabled: number
    role: string
    jwtToken: JwtToken
  }

  export interface JwtToken {
    access_token: string
    access_expire: number
    refresh_after: number
  }
}

namespace API_PostChangePassword {
  export interface Result {
    err: number
    msg: string
    res: Res
  }
}

namespace API_RefreshToken {
  export interface Result {
    err: number
    msg: string
    res: Res
  }
  export interface Res {
    access_token: string
    access_expire: number
    refresh_after: number
  }
}
