// Generated by https://quicktype.io

declare namespace API_PostDeviceList {
  export interface Result {
    err: number
    msg: string
    res: Res
  }

  export interface Res {
    has_more: number
    next_page: number
    total: number
    list: List[]
  }

  export interface List {
    id: number
    ip: string
    name: string
    position: string
    type: string
    status: bigint
    status_text: string
    temperature: number
    current: number
    voltage: number
    is_maintaining: boolean
  }
}

declare namespace API_PostDeviceCreate {
  export interface Result {
    err: number
    msg: string
    res: Res
  }

  export interface Res {}
}
declare namespace API_PostDeviceUpdate {
  export interface Result {
    err: number
    msg: string
    res: Res
  }

  export interface Res {}
}

declare namespace API_PostToggleMaintaining{
  export interface Result {
    err: number
    msg: string
    res: Res
  }

  export interface Res {}
}

declare namespace API_PostDeviceTypes {
  export interface Result {
    err: number
    msg: string
    res: Res
  }

  export interface Res {
    list: List[]
  }

  export interface List {
    key: string
    value: string
  }
}
